### findProduct
GET http://localhost:8080/products/1

### findAllProducts
GET http://localhost:8080/products

### createProduct
POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "test_c77bb58650c3",
  "price": 7.97,
  "stock": 12
}

### updateProduct
PUT http://localhost:8080/products/9
Content-Type: application/json

{
  "name": "Novo nome",
  "price": 8.00,
  "stock": 12
}

### deleteProduct
DELETE http://localhost:8080/products/9

### checkout
POST http://localhost:8080/orders
Content-Type: application/json

{
  "productOrderRequestList": [
    {
      "productId": 1,
      "price": 12.50,
      "quantity": 2
    },
    {
      "productId": 4,
      "price": 8.00,
      "quantity": 12
    }
  ]
}